/*package com.example.myapplication
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.SQLException
object DataManager {
    fun insertData(nombre: String, correo:String, contra:String, tipo:Int, telefono:Int) {
        try {
            //val connection: Connection = Conexion.getConnection()
            val query = "INSERT INTO cliente (nombre,correo,contrasena,tipo,telefono) VALUES (?,?,?,0,?)"
            //val preparedStatement: PreparedStatement = connection.prepareStatement(query)
            //preparedStatement.setString(1, nombre)
            //preparedStatement.setString(2, correo)
            //preparedStatement.setString(3, contra)
            //preparedStatement.setInt(4, tipo)
            //preparedStatement.setInt(5, telefono)
            //preparedStatement.executeUpdate()
            //preparedStatement.close()
            //connection.close()
        } catch (e: SQLException) {
            e.printStackTrace()
        }
    }
}*/
